### PR TITLE
upgrade to julia 1.0

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I don't really get, why numbers are encoded with different types depending on the numbers range.
That seems to be against user intent, and also this way we can't opt-out... If one would respect the Julia number types, one could control this behavior a 100%.

Also, if we turn [this line](https://github.com/saurvs/CBOR.jl/blob/master/src/decoding-common.jl#L217) into a map, we could use Julia's automatic vector type promotion to get tightly typed arrays back.
This would need the consideration from my first point, since otherwise `[1, 258, -1]` will come back as `Integer[0x00, 0x0102, -1]` which I can't imagine anyone would ever want!

**Comment by SimonDanisch** [comment]
Btw, @saurvs if you don't want to continue maintaining CBOR.jl, feel free to move it to JuliaIO!
In JuliaIO, others and I can continue maintenance more easily ;)

**Comment by chakravala** [comment]
this would definitely be a good package to keep around and available

**Comment by saurvs** [comment]
@SimonDanisch I haven't worked with Julia in nearly 2 years, and hence can't review this or other PRs effectively. So I think moving this repo to JuliaIO is a good idea. But I think you'll need to give me permission to create a new repo on JuliaIO. As soon as you do that I'll transfer it.

**Comment by SimonDanisch** [comment]
Great! I invited you to JuliaIO!
If member access is not enough to transfer the repository, let me know!

**Comment by saurvs** [comment]
@SimonDanisch great! The transfer is done.

**Comment by SimonDanisch** [comment]
awesome, thanks a lot :)

**Comment by SimonDanisch** [comment]
@stevengj & @chakravala what do you think about my proposed changes concerning preserving types & arrays?

**Pull request merged**
